Repository zilliztech/GPTCache, pull requests merged in 2023-08, with the labels that each got.

#502 NumpyNormEvaluation numpy error fix
  gptcache/similarity_evaluation/np.py
Labels: needs-dco, size/XS

#505 Small package name fix in test's requirement.txt file
  tests/requirements.txt
Labels: needs-dco, size/XS

#507 Add the static method for the azure openai
  gptcache/core.py
  gptcache/utils/__init__.py
Labels: dco-passed, approved, size/S

#508 LangChainLLMs cache_obj update
  gptcache/adapter/langchain_models.py
  tests/unit_tests/adapter/test_langchain_models.py
Labels: needs-dco, size/S

#510 Use the fixed version of usearch lib
  gptcache/utils/__init__.py
Labels: dco-passed, approved, size/XS

#514 Fix the wrong search result of the pgvector
  gptcache/__init__.py
  gptcache/manager/vector_data/pgvector.py
  tests/unit_tests/manager/test_pgvector.py
Labels: dco-passed, ci-passed, approved, size/S

#515 Fix backwards search results in pgvector.py
  gptcache/manager/vector_data/pgvector.py
Labels: needs-dco, size/XS

#516 Update the test case of pgvector store
  gptcache/__init__.py
  tests/unit_tests/manager/test_pgvector.py
Labels: dco-passed, ci-passed, approved, size/XS

#518 Distributed cache feature using Redis
  examples/eviction/distributed_eviction.py
  gptcache/manager/data_manager.py
  gptcache/manager/eviction/distributed_cache.py
  gptcache/manager/eviction/manager.py
  gptcache/manager/eviction/memory_cache.py
  gptcache/manager/factory.py
  gptcache/manager/scalar_data/redis_storage.py
  tests/unit_tests/eviction/test_distributed_cache.py
  tests/unit_tests/manager/test_redis_cache_storage.py
Labels: dco-passed, ci-passed, approved, lgtm, size/XL

#522 [fix] Failed to import gptcache due to missing redis dependency
  gptcache/manager/eviction/distributed_cache.py
  gptcache/manager/eviction/manager.py
  gptcache/manager/eviction/redis_eviction.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm
