Repository zilliztech/GPTCache, pull requests merged in 2023-05, with the labels that each got.

#316 Add SummarizationContextProcess
  examples/context_examples/summarization_context.py
  gptcache/processor/context/summarization_context.py
  tests/unit_tests/processor/test_summarize_context.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#323 Support duckdb
  README.md
  gptcache/manager/factory.py
  gptcache/manager/scalar_data/__init__.py
  gptcache/manager/scalar_data/manager.py
  gptcache/manager/scalar_data/sql_storage.py
  gptcache/utils/__init__.py
  tests/unit_tests/adapter/test_openai.py
  tests/unit_tests/manager/test_sql_scalar.py
Labels: dco-passed, ci-passed, approved, size/L

#325 Add cmd for gptcache server
  gptcache_server/server.py
  setup.py
Labels: dco-passed, size/S

#327 Update langchain llms with session
  docs/bootcamp/langchain/qa_generation.ipynb
  docs/bootcamp/langchain/sqlite.ipynb
  examples/README.md
  gptcache/adapter/langchain_models.py
Labels: dco-passed, approved, size/M, lgtm

#329 Wrap gptcache server in a docker image
  gptcache_server/dockerfiles/Dockerfile
Labels: dco-passed, size/S

#330 Fix requirements conflict for sphinx
  docs/requirements.txt
Labels: dco-passed, size/XS

#331 Use self-hosted tokenizer and update summarization context.
  examples/context_examples/summarization_context.py
  gptcache/embedding/__init__.py
  gptcache/embedding/huggingface.py
  gptcache/embedding/onnx.py
  gptcache/embedding/sbert.py
  gptcache/processor/context/summarization_context.py
  tests/unit_tests/embedding/test_huggingface.py
  tests/unit_tests/embedding/test_sbert.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#333 Optimize some code
  gptcache/adapter/api.py
  gptcache/core.py
  gptcache/session.py
Labels: dco-passed, ci-passed, approved, size/M

#334 Add BabyAGI bootcamp
  docs/bootcamp/langchain/baby_agi.ipynb
  docs/toc.bak
Labels: dco-passed, size/L

#337 Support the langchain embeddings
  examples/context_examples/summarization_context.py
  gptcache/embedding/__init__.py
  gptcache/embedding/langchain.py
  tests/requirements.txt
  tests/unit_tests/embedding/test_langchain.py
Labels: dco-passed, ci-passed, approved, size/M

#338 Add gptcache client
  gptcache/__init__.py
  gptcache/client.py
  gptcache/utils/__init__.py
  tests/pytest.ini
  tests/unit_tests/test_client.py
Labels: dco-passed, ci-passed, size/M

#341 Fix the ci error about the langchain
  gptcache/adapter/langchain_models.py
Labels: dco-passed, ci-passed, approved, size/XS

#339 Support pgvector as vector store.
  .github/workflows/unit_test_main.yaml
  README.md
  gptcache/manager/vector_data/__init__.py
  gptcache/manager/vector_data/manager.py
  gptcache/manager/vector_data/pgvector.py
  tests/requirements.txt
  tests/unit_tests/manager/test_pgvector.py
Labels: dco-passed, size/L

#347 Update the version to `0.1.24`
  docs/release_note.md
  gptcache/adapter/openai.py
  gptcache/core.py
  gptcache/embedding/__init__.py
  gptcache/embedding/openai.py
  gptcache/manager/vector_data/manager.py
  gptcache/utils/__init__.py
  requirements.txt
  setup.py
Labels: dco-passed, ci-passed, approved, size/M

#345 [skip ci]Add workflow to publish release image
  .github/workflows/publish_release_image.yaml
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#348 Update the doc directory
  README.md
  docs/_exts/docgen.py
  docs/bootcamp/langchain/index.rst
  docs/bootcamp/openai/index.rst
  docs/bootcamp/replicate/index.rst
  docs/bootcamp/temperature/index.rst
  docs/requirements.txt
  docs/toc.bak
  gptcache/adapter/openai.py
  gptcache/manager/vector_data/chroma.py
  gptcache/utils/__init__.py
Labels: dco-passed, ci-passed, approved, size/L

#349 Add the docker image doc
  README.md
  docs/_exts/docgen.py
  docs/feature.md
  docs/release_note.md
  docs/toc.bak
  docs/usage.md
  examples/README.md
Labels: dco-passed, approved, size/M

#351 DocArray as a vectorstore
  examples/data_manager/vector_store.py
  gptcache/manager/vector_data/__init__.py
  gptcache/manager/vector_data/chroma.py
  gptcache/manager/vector_data/docarray_index.py
  gptcache/manager/vector_data/faiss.py
  gptcache/manager/vector_data/hnswlib_store.py
  gptcache/manager/vector_data/manager.py
  gptcache/manager/vector_data/milvus.py
  gptcache/manager/vector_data/pgvector.py
  gptcache/utils/__init__.py
  tests/unit_tests/manager/test_local_index.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#352 Fix the doc generation failure
  .github/workflows/pylint.yaml
  .gitignore
  README.md
  docs/Makefile
  docs/_exts/indexCon.py
  docs/conf.py
  docs/index.rst
  docs/references/index.rst
  docs/usage.md
  examples/README.md
Labels: dco-passed, approved, size/XL

#353 Replace base image and simplify dockerfile
  gptcache_server/dockerfiles/Dockerfile
Labels: dco-passed, approved, lgtm, size/S

#354 Example with DocArray
  docs/bootcamp/openai/tweet_classifier.ipynb
  gptcache/manager/vector_data/docarray_index.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#355 Add comments for session
  gptcache/processor/check_hit.py
  gptcache/session.py
Labels: dco-passed, ci-passed, approved, lgtm, size/S

#356 DocArray example adjustment
  docs/bootcamp/openai/index.rst
  docs/bootcamp/openai/tweet_classifier.ipynb
Labels: dco-passed, size/S

#358 Improve the generation doc script
  README.md
  docs/_exts/docgen.py
  docs/conf.py
  docs/index.rst
  docs/usage.md
  examples/README.md
  gptcache/__init__.py
  gptcache/client.py
  gptcache/config.py
  gptcache/core.py
  gptcache/embedding/huggingface.py
  gptcache/embedding/string.py
  gptcache/processor/pre.py
  gptcache/utils/__init__.py
Labels: dco-passed, approved, size/L

#362 Change the model test cases as L2 cases
  tests/integration_tests/test_sqlite_faiss_onnx.py
  tests/unit_tests/adapter/test_diffusers.py
  tests/unit_tests/adapter/test_dolly.py
  tests/unit_tests/adapter/test_replicate.py
  tests/unit_tests/adapter/test_stability.py
  tests/unit_tests/embedding/test_data2vec.py
  tests/unit_tests/embedding/test_sbert.py
  tests/unit_tests/embedding/test_timm.py
  tests/unit_tests/embedding/test_vit.py
  tests/unit_tests/processor/test_selective_context.py
Labels: dco-passed, ci-passed, approved, size/M

#365 Add concat_context.
  gptcache/processor/context/concat_context.py
  gptcache/processor/context/summarization_context.py
  tests/unit_tests/processor/test_concat_context.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#364 Add the pre/report/session docs
  docs/_exts/docgen.py
  gptcache/embedding/base.py
  gptcache/processor/context/context.py
  gptcache/processor/pre.py
  gptcache/report.py
  gptcache/session.py
  gptcache/similarity_evaluation/similarity_evaluation.py
  tests/unit_tests/processor/test_summarize_context.py
Labels: dco-passed, ci-passed, approved, size/L

#363 Add rwkv model for embedding.
  gptcache/adapter/api.py
  gptcache/embedding/__init__.py
  gptcache/embedding/rwkv.py
  tests/unit_tests/embedding/test_rwkv.py
Labels: dco-passed, size/M

#367 Update the version to `0.1.25`
  .github/workflows/Nightly_CI_main.yaml
  .github/workflows/pylint.yaml
  .github/workflows/unit_test_main.yaml
  docs/release_note.md
  gptcache/embedding/__init__.py
  gptcache/embedding/rwkv.py
  gptcache/manager/factory.py
  gptcache/processor/context/summarization_context.py
  setup.py
  tests/unit_tests/embedding/test_rwkv.py
  tests/unit_tests/manager/test_chromadb.py
  tests/unit_tests/manager/test_local_index.py
  tests/unit_tests/manager/test_pgvector.py
Labels: dco-passed, approved, size/L

#368 Replace summarization test model.
  tests/unit_tests/processor/test_summarize_context.py
Labels: dco-passed, size/XS

#371 Add the llama index bootcamp
  README.md
  docs/bootcamp/llama_index/index.rst
  docs/bootcamp/llama_index/webpage_qa.ipynb
Labels: dco-passed, approved, size/L

#372 Update the llama index example url
  README.md
  docs/index.rst
  docs/toc.bak
Labels: dco-passed, approved, size/XS

#376 Support the openai moderation adapter
  examples/processor/temperature_example.py
  gptcache/adapter/adapter.py
  gptcache/adapter/openai.py
  gptcache/config.py
  gptcache/embedding/huggingface.py
  gptcache/processor/pre.py
  tests/unit_tests/adapter/test_openai.py
  tests/unit_tests/processor/test_post.py
  tests/unit_tests/processor/test_pre.py
Labels: dco-passed, approved, size/L

#380 Update the cache config template file and example directory
  cache_config_template.yml
  examples/README.md
  examples/context_process/selective_context.py
  examples/context_process/summarization_context.py
  examples/integrate/diffusers/stable_diffusion.py
  examples/integrate/dolly/basic_usage.py
  examples/integrate/langchain/langchain_llms_mock.py
  examples/integrate/langchain/langchain_prompt_openai.py
  examples/integrate/langchain/langchain_similaritycache_openai.py
  examples/integrate/llama_cpp/basic_usage.py
  examples/integrate/openai/basic_usage.py
  examples/integrate/openai/create_image.py
  examples/integrate/openai/qa.py
  examples/integrate/openai/readme.py
  examples/integrate/openai/summarize.py
  examples/integrate/replicate/vqa.py
  examples/integrate/stability/text_to_image.py
  tests/requirements.txt
Labels: dco-passed, ci-passed, approved, size/S

#381 Fix the wrong LangChainChat comment
  examples/integrate/langchain/langchain_qa_chain.py
  examples/integrate/langchain/langchain_similaritycache_openai.py
  gptcache/adapter/api.py
  gptcache/adapter/langchain_models.py
  gptcache/processor/pre.py
  tests/unit_tests/processor/test_pre.py
Labels: dco-passed, ci-passed, approved, size/M

#382 Add UForm multi-modal embedding
  gptcache/embedding/uform.py
  gptcache/utils/__init__.py
  tests/unit_tests/embedding/test_data2vec.py
  tests/unit_tests/embedding/test_rwkv.py
  tests/unit_tests/embedding/test_sbert.py
  tests/unit_tests/embedding/test_uform.py
Labels: dco-passed, ci-passed, approved, size/L

#383 Support to config the cache storage data size
  docs/_exts/docgen.py
  docs/requirements.txt
  gptcache/manager/scalar_data/__init__.py
  gptcache/manager/scalar_data/manager.py
  gptcache/manager/scalar_data/sql_storage.py
  tests/requirements.txt
  tests/unit_tests/manager/test_sql_scalar.py
Labels: dco-passed, ci-passed, approved, size/L

#387 Update the protobuf version in the doc
  docs/requirements.txt
Labels: dco-passed, approved, size/XS

#394 Add the BaseCacheLLM abstract class to wrap the llm
  gptcache/adapter/api.py
  gptcache/adapter/base.py
  gptcache/adapter/diffusers.py
  gptcache/adapter/dolly.py
  gptcache/adapter/langchain_models.py
  gptcache/adapter/llama_cpp.py
  gptcache/adapter/minigpt4.py
  gptcache/adapter/openai.py
  gptcache/adapter/stability_sdk.py
  gptcache/manager/object_data/__init__.py
  gptcache/manager/object_data/manager.py
  gptcache/manager/scalar_data/__init__.py
  gptcache/manager/scalar_data/manager.py
  gptcache/manager/vector_data/__init__.py
  gptcache/manager/vector_data/manager.py
  gptcache/manager/vector_data/pgvector.py
  tests/unit_tests/adapter/test_langchain_models.py
  tests/unit_tests/adapter/test_openai.py
  tests/unit_tests/adapter/test_stability.py
Labels: dco-passed, ci-passed, approved, size/XL

#395 Add the pre-function of handling long prompt and Update context doc
  docs/conf.py
  gptcache/adapter/adapter.py
  gptcache/config.py
  gptcache/processor/context/concat_context.py
  gptcache/processor/context/selective_context.py
  gptcache/processor/context/summarization_context.py
  gptcache/processor/pre.py
  tests/unit_tests/adapter/test_langchain_models.py
Labels: dco-passed, ci-passed, approved, size/L

#396 Support to config the context pre-process by the yaml file
  cache_config_template.yml
  docs/release_note.md
  examples/README.md
  examples/context_process/selective_context.py
  examples/context_process/summarization_context.py
  gptcache/adapter/api.py
  gptcache/processor/context/__init__.py
  gptcache/processor/context/summarization_context.py
  tests/unit_tests/adapter/test_api.py
  tests/unit_tests/processor/test_concat_context.py
  tests/unit_tests/processor/test_selective_context.py
  tests/unit_tests/processor/test_summarize_context.py
Labels: dco-passed, approved, size/L

#397 Improve the unit test flow
  .github/workflows/unit_test_main.yaml
  docs/_exts/docgen2.py
  tests/requirements.txt
Labels: dco-passed, ci-passed, approved, size/M
