Repository zilliztech/GPTCache, pull requests merged in 2023-04, with the labels that each got.

#21 Update README.md
  README.md
Labels: dco-passed, do-not-merge/missing-related-issue

#23 Update README.md
  README.md
Labels: dco-passed, do-not-merge/missing-related-issue

#25 Update README.md
  README.md
Labels: dco-passed, do-not-merge/missing-related-issue, approved, size/M

#26 [skip ci] update mergify
  .github/mergify.yml
Labels: dco-passed, ci-passed, approved, size/M, lgtm, kind/improvement

#27 [skip ci]Add workflow to upload GPTCache package
  .github/workflows/publish_dev_package.yaml
Labels: dco-passed, size/M

#28 [skip ci]Add workflow to upload GPTCache package
  .github/workflows/publish_dev_package.yaml
Labels: dco-passed, size/S

#20 add badge
  .github/workflows/CI_main.yaml
  README.md
Labels: dco-passed, do-not-merge/missing-related-issue, ci-passed, approved, size/M, lgtm

#34 add badge
  README.md
Labels: dco-passed, size/M

#33 update arch chat
  docs/GPTCacheStructure.png
Labels: dco-passed, size/XS

#35 Add chromadb
  examples/sqlite_chromadb_mock/sqlite_chromadb_mock.py
  gptcache/cache/data_manager.py
  gptcache/cache/factory.py
  gptcache/cache/vector_data/__init__.py
  gptcache/cache/vector_data/chromadb.py
  gptcache/util/__init__.py
  tests/integration_tests/cache/vector_data/test_chromadb.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#38 add llm
  examples/langchian_llms_mock/langchian_llms_mock.py
  gptcache/adapter/langchain_llms.py
  gptcache/processor/post.py
  gptcache/processor/pre.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#32 [skip ci] update workflow
  .github/mergify.yml
  .github/workflows/publish_dev_package.yaml
Labels: dco-passed, size/S

#41 Add `SimilarityEvaluation` interface for fixed threshold range
  README.md
  examples/benchmark/benchmark_sqlite_faiss_towhee.py
  examples/openai_request/openai_request.py
  examples/sqlite_faiss_mock/sqlite_faiss_mock.py
  examples/sqlite_faiss_towhee/sqlite_faiss_towhee.py
  examples/sqlite_milvus_mock/sqlite_milvus_mock.py
  gptcache/adapter/adapter.py
  gptcache/cache/data_manager.py
  gptcache/core.py
  gptcache/ranker/np.py
  gptcache/ranker/similarity_evaluation.py
  gptcache/ranker/simple.py
  gptcache/ranker/string.py
  gptcache/ranker/towhee.py
  setup.py
  tests/integration_tests/test_sqlite_faiss_towhee.py
Labels: dco-passed, ci-passed, approved, size/L

#42 Update the module part of ReadMe
  README.md
Labels: dco-passed, size/M

#43 Rename `chromadb` to `chroma`
  gptcache/cache/vector_data/__init__.py
  gptcache/cache/vector_data/base.py
  gptcache/cache/vector_data/chroma.py
  tests/unit_tests/cache/vector_data/test_chromadb.py
Labels: dco-passed, ci-passed, approved, kind/improvement, size/S

#46 Add sqlalchemy for sql db
  gptcache/cache/data_manager.py
  gptcache/cache/eviction.py
  gptcache/cache/factory.py
  gptcache/cache/scalar_data/base.py
  gptcache/cache/scalar_data/scalar_store.py
  gptcache/cache/scalar_data/sqlalchemy.py
  gptcache/cache/scalar_data/sqllite3.py
  gptcache/util/__init__.py
Labels: dco-passed, size/L

#47 Add SQLDataBase with lazy import
  gptcache/cache/factory.py
  gptcache/cache/scalar_data/__init__.py
  gptcache/cache/scalar_data/sqlalchemy.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#48 Rename the dir name and add the unittest dir
  .gitignore
  docs/contributing.md
  examples/benchmark/benchmark_sqlite_faiss_towhee.py
  examples/langchian_llms_mock/langchian_llms_mock.py
  examples/openai_request/openai_request.py
  examples/sqlite_chromadb_mock/sqlite_chromadb_mock.py
  examples/sqlite_faiss_mock/sqlite_faiss_mock.py
  examples/sqlite_faiss_towhee/sqlite_faiss_towhee.py
  examples/sqlite_milvus_mock/sqlite_milvus_mock.py
  gptcache/adapter/adapter.py
  gptcache/cache/data_manager.py
  gptcache/cache/factory.py
  gptcache/cache/scalar_data/__init__.py
  gptcache/cache/scalar_data/sqlalchemy.py
  gptcache/cache/vector_data/__init__.py
  gptcache/cache/vector_data/chroma.py
  gptcache/cache/vector_data/faiss.py
  gptcache/cache/vector_data/milvus.py
  gptcache/core.py
  gptcache/embedding/__init__.py
  gptcache/embedding/openai.py
  gptcache/embedding/string.py
  gptcache/embedding/towhee.py
  gptcache/encoder/__init__.py
  gptcache/ranker/__init__.py
  gptcache/similarity_evaluation/__init__.py
  gptcache/similarity_evaluation/np.py
  gptcache/similarity_evaluation/similarity_evaluation.py
  gptcache/similarity_evaluation/simple.py
  gptcache/similarity_evaluation/string.py
  gptcache/similarity_evaluation/towhee.py
  gptcache/utils/__init__.py
  gptcache/utils/dependency_control.py
  gptcache/utils/error.py
  gptcache/utils/lazy_import.py
  scripts/manage_conda_env.sh
  scripts/remove_example_cache.sh
  tests/integration_tests/test_sqlite_faiss_towhee.py
  tests/unit_tests/cache/test_chromadb.py
  tests/unit_tests/test_core.py
Labels: dco-passed, ci-passed, approved, size/L, kind/improvement

#52 add more badges and doc update
  README.md
Labels: dco-passed, size/XS

#53 Add `core` unit test
  tests/unit_tests/test_core.py
Labels: dco-passed, ci-passed, approved, size/M, kind/improvement

#54 Add python version tests
  .github/workflows/CI_integration_test_main.yaml
  .github/workflows/CI_main.yaml
  .github/workflows/unit_test_main.yaml
Labels: dco-passed, size/S

#57 update workflow
  .github/workflows/build_dev_python_package.yaml
  .github/workflows/publish_dev_package.yaml
  .github/workflows/publish_release_package.yaml
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#56 replace model with lite onnx implementation.
  README.md
  docs/system.md
  docs/usage.md
  examples/example.md
  examples/sqlite_faiss_towhee/sqlite_faiss_towhee.py
  gptcache/embedding/__init__.py
  gptcache/embedding/towhee.py
  gptcache/similarity_evaluation/towhee.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#60 update workflow for publish package
  .github/mergify.yml
  .github/workflows/publish_dev_package.yaml
  .github/workflows/publish_release_package.yaml
Labels: dco-passed, ci-passed, approved, lgtm

#62 Get Some Examples from OpenAI
  examples/openai_examples/qa.py
  examples/openai_examples/summarize.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#58 Docs support by sphinx
  docs/Makefile
  docs/conf.py
  docs/contributing.md
  docs/index.rst
  docs/make.bat
  docs/markdown/gptcache/__init__.md
  docs/markdown/gptcache/cache/__init__.md
  docs/markdown/gptcache/cache/data_manager.md
  docs/markdown/gptcache/cache/factory.md
  docs/markdown/gptcache/core.md
  docs/markdown/index.rst
  docs/markdown/requirements.md
  docs/markdown/setup.md
  docs/module.md
  docs/quick-start.md
  docs/references/gptcache/embedding.rst
  docs/references/index.rst
  docs/requirements.txt
  gptcache/embedding/__init__.py
  gptcache/embedding/openai.py
  gptcache/embedding/towhee.py
Labels: dco-passed, ci-passed, approved, lgtm, size/XL

#63 Add the unit test for common module
  gptcache/similarity_evaluation/np.py
  gptcache/similarity_evaluation/towhee.py
  tests/unit_tests/adapter/test_adapter.py
  tests/unit_tests/embedding/test_embedding_string.py
  tests/unit_tests/embedding/test_towhee.py
  tests/unit_tests/processor/test_post.py
  tests/unit_tests/processor/test_pre.py
  tests/unit_tests/similarity_evaluation/test_evaluation_string.py
  tests/unit_tests/similarity_evaluation/test_evaluation_towhee.py
  tests/unit_tests/similarity_evaluation/test_np.py
  tests/unit_tests/similarity_evaluation/test_simple.py
  tests/unit_tests/utils/test_error.py
Labels: dco-passed, ci-passed, approved, size/L

#65 Update arch chart
  docs/GPTCacheStructure.png
Labels: dco-passed, size/XS, kind/improvement

#59 Add params tests
  tests/integration_tests/test_sqlite_faiss_towhee.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#66 Add huggingface in embedding
  docs/references/gptcache/embedding.rst
  docs/usage.md
  examples/benchmark/benchmark_sqlite_faiss_towhee.py
  examples/openai_request/openai_request.py
  examples/sqlite_faiss_towhee/sqlite_faiss_towhee.py
  gptcache/embedding/__init__.py
  gptcache/embedding/huggingface.py
  gptcache/embedding/openai.py
  gptcache/embedding/towhee.py
  gptcache/utils/__init__.py
  tests/integration_tests/test_sqlite_faiss_towhee.py
  tests/unit_tests/embedding/test_huggingface.py
  tests/unit_tests/embedding/test_towhee.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#67 Add example for sqlalchemy
  .gitignore
  README.md
  examples/mariadb_faiss_mock/mariadb_faiss_mock.py
  examples/mssql_faiss_mock/mssql_faiss_mock.py
  examples/mysql_faiss_mock/mysql_faiss_mock.py
  examples/oracle_faiss_mock/oracle_faiss_mock.py
  examples/postgresql_faiss_mock/postgresql_faiss_mock.py
  gptcache/cache/factory.py
  gptcache/cache/scalar_data/__init__.py
  gptcache/cache/scalar_data/base.py
  gptcache/cache/scalar_data/sqlalchemy.py
  gptcache/utils/__init__.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#69 Add sbert embedding
  docs/conf.py
  docs/references/gptcache/embedding.rst
  docs/requirements.txt
  gptcache/embedding/__init__.py
  gptcache/embedding/sbert.py
  gptcache/utils/__init__.py
  tests/unit_tests/embedding/test_sbert.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#71 Add the example code to the readme doc
  README.md
  examples/langchian_llms_mock/langchian_llms_mock.py
  examples/openai_examples/basic_usage.py
  examples/openai_examples/readme.py
  gptcache/core.py
Labels: dco-passed, approved, size/L

#68 Add common test files
  tests/integration_tests/base/client_base.py
  tests/integration_tests/common/common_func.py
  tests/integration_tests/common/common_type.py
  tests/integration_tests/config/log_config.py
  tests/integration_tests/test_sqlite_faiss_towhee.py
  tests/integration_tests/utils/util_log.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#72 Add params in docstring
  docs/references/gptcache/embedding.rst
  gptcache/embedding/huggingface.py
  gptcache/embedding/openai.py
  gptcache/embedding/sbert.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#73 Add the unit test for map data manager and adapter
  tests/unit_tests/adapter/test_adapter.py
  tests/unit_tests/cache/test_map.py
Labels: dco-passed, ci-passed, approved, size/M

#75 Update the hint for running the example
  examples/README.md
Labels: dco-passed, approved, size/XS

#76 Add cohere embedding
  docs/references/gptcache/embedding.rst
  gptcache/embedding/__init__.py
  gptcache/embedding/cohere.py
  gptcache/utils/__init__.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#74 add onnx embedding.
  gptcache/embedding/__init__.py
  gptcache/embedding/onnx.py
  gptcache/similarity_evaluation/__init__.py
  gptcache/similarity_evaluation/onnx.py
  gptcache/utils/__init__.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#78 Debug the langchain llms model
  examples/langchian_llms_mock/langchian_llms_mock.py
  gptcache/adapter/langchain_llms.py
  gptcache/core.py
  gptcache/processor/pre.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#81 Use the onnx model in the readme example
  README.md
  gptcache/utils/dependency_control.py
  scripts/manage_conda_env.sh
  scripts/remove_example_cache.sh
  setup.py
Labels: dco-passed, ci-passed, approved, size/M

#82 Fix HBase typo
  README.md
Labels: dco-passed, size/XS

#86 Update chat
  docs/GPTCache.png
Labels: dco-passed, size/XS, kind/improvement

#85 Modify the docs to use onnx as default embedding encoder.
  README.md
  docs/contributing.md
  docs/index.rst
  docs/module.md
  docs/quick-start.md
  docs/system.md
  docs/usage.md
  examples/README.md
Labels: dco-passed, size/L

#84 Add Docstring for datamanager
  gptcache/cache/data_manager.py
  gptcache/cache/factory.py
  gptcache/cache/scalar_data/base.py
  gptcache/cache/scalar_data/sqlalchemy.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#89 minor changes to readme
  README.md
Labels: dco-passed, size/S

#87 Add Nightly CI
  .github/workflows/Nightly_CI_main.yaml
  tests/integration_tests/test_sqlite_faiss_onnx.py
  tests/requirements.txt
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#88 Add fasttext
  docs/references/embedding.rst
  gptcache/embedding/__init__.py
  gptcache/embedding/fasttext.py
  gptcache/utils/__init__.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#90 Rename data manager
  examples/README.md
  examples/benchmark/benchmark_sqlite_faiss_onnx.py
  examples/map/map.py
  examples/mariadb_milvus_mock/mariadb_milvus_mock.py
  examples/mssql_milvus_mock/mssql_milvus_mock.py
  examples/mysql_milvus_mock/mysql_milvus_mock.py
  examples/openai_examples/basic_usage.py
  examples/openai_examples/readme.py
  examples/oracle_milvus_mock/oracle_milvus_mock.py
  examples/postgresql_milvus_mock/postgresql_milvus_mock.py
  examples/sqlite_chromadb_mock/sqlite_chromadb_mock.py
  examples/sqlite_faiss_mock/sqlite_faiss_mock.py
  examples/sqlite_faiss_onnx/sqlite_faiss_onnx.py
  examples/sqlite_milvus_mock/sqlite_milvus_mock.py
  gptcache/cache/factory.py
  gptcache/core.py
  tests/integration_tests/test_sqlite_faiss_onnx.py
  tests/requirements.txt
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#91 Update docs
  docs/autodoc_md/gptcache/__init__.md
  docs/autodoc_md/gptcache/cache/__init__.md
  docs/autodoc_md/gptcache/cache/data_manager.md
  docs/autodoc_md/gptcache/cache/factory.md
  docs/autodoc_md/gptcache/core.md
  docs/autodoc_md/index.rst
  docs/autodoc_md/requirements.md
  docs/autodoc_md/setup.md
  docs/contributing.md
  docs/index.rst
  docs/module.md
  docs/quick-start.md
  docs/references/adapter.rst
  docs/references/cache.rst
  docs/references/core.rst
  docs/references/index.rst
  docs/references/processor.rst
  docs/references/similarity_evaluation.rst
  docs/references/utils.rst
  docs/system.md
Labels: dco-passed, size/L

#93 Modify CI files
  .github/workflows/CI_main.yaml
  tests/integration_tests/examples/map/map.py
  tests/integration_tests/examples/sqlite_faiss_mock/sqlite_faiss_mock.py
  tests/integration_tests/examples/sqlite_faiss_onnx/sqlite_faiss_onnx.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#94 Update doc
  docs/index.rst
  docs/references/core.rst
  docs/references/index.rst
  gptcache/core.py
  gptcache/similarity_evaluation/onnx.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#96 Fix api inference
  docs/references/cache.rst
  docs/references/core.rst
Labels: dco-passed, size/S

#98 Fix doc
  README.md
Labels: dco-passed, size/XS, kind/improvement

#97 Update eviction for fifo
  gptcache/cache/data_manager.py
  gptcache/cache/eviction.py
  gptcache/cache/factory.py
  gptcache/cache/scalar_data/base.py
  gptcache/cache/scalar_data/sqlalchemy.py
  gptcache/cache/vector_data/milvus.py
  tests/unit_tests/cache/test_eviction.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#92 Update the example files
  README.md
  examples/README.md
  examples/adapter/langchain_llms.py
  examples/adapter/openai_chatgpt.py
  examples/benchmark/benchmark_sqlite_faiss_onnx.py
  examples/data_manager/map_manager.py
  examples/data_manager/scalar_store.py
  examples/data_manager/vector_store.py
  examples/embedding/default.py
  examples/embedding/onnx.py
  examples/embedding/random.py
  examples/map/map.py
  examples/mariadb_milvus_mock/mariadb_milvus_mock.py
  examples/mssql_milvus_mock/mssql_milvus_mock.py
  examples/mysql_milvus_mock/mysql_milvus_mock.py
  examples/openai_examples/basic_usage.py
  examples/openai_examples/readme.py
  examples/oracle_milvus_mock/oracle_milvus_mock.py
  examples/postgresql_milvus_mock/postgresql_milvus_mock.py
  examples/similarity_evaluation/exact_match.py
  examples/similarity_evaluation/onnx.py
  examples/similarity_evaluation/search_distance.py
  examples/sqlite_chromadb_mock/sqlite_chromadb_mock.py
  examples/sqlite_faiss_mock/sqlite_faiss_mock.py
  examples/sqlite_faiss_onnx/sqlite_faiss_onnx.py
  examples/sqlite_milvus_mock/sqlite_milvus_mock.py
  gptcache/core.py
  gptcache/similarity_evaluation/distance.py
  gptcache/similarity_evaluation/exact_match.py
  setup.py
  tests/integration_tests/examples/sqlite_faiss_mock/sqlite_faiss_mock.py
  tests/integration_tests/examples/sqlite_faiss_onnx/sqlite_faiss_onnx.py
  tests/integration_tests/test_sqlite_faiss_onnx.py
  tests/unit_tests/similarity_evaluation/test_evaluation_string.py
  tests/unit_tests/similarity_evaluation/test_simple.py
Labels: dco-passed, ci-passed, approved, size/XL

#102 Improve chart
  docs/GPTCacheStructure.png
Labels: dco-passed, size/XS, kind/improvement

#104 Improve text, gpt cache -> GPTCache
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  README.md
  examples/openai_examples/readme.py
  examples/openai_examples/summarize.py
Labels: dco-passed, ci-passed, size/M, kind/improvement

#105 Support Langchain as the interface
  README.md
  examples/langchain_examples/langchain_prompt_openai.py
  examples/langchain_examples/langchain_similaritycache_openai.py
  examples/langchain_examples/langchian_llms_mock.py
  gptcache/adapter/adapter.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#103 Add docstring for similarity_evaluation.
  examples/benchmark/benchmark_sqlite_faiss_onnx.py
  gptcache/embedding/onnx.py
  gptcache/similarity_evaluation/__init__.py
  gptcache/similarity_evaluation/distance.py
  gptcache/similarity_evaluation/exact_match.py
  gptcache/similarity_evaluation/np.py
  gptcache/similarity_evaluation/onnx.py
  tests/unit_tests/similarity_evaluation/test_evaluation_onnx.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#108 Fix docstring for similarity_evaluation
  README.md
  docs/index.rst
  docs/modules/embedding_generator.md
  docs/references/adapter.rst
  docs/references/cache.rst
  docs/references/core.rst
  docs/references/processor.rst
  docs/references/similarity_evaluation.rst
  gptcache/similarity_evaluation/distance.py
  gptcache/similarity_evaluation/exact_match.py
  gptcache/similarity_evaluation/np.py
  gptcache/similarity_evaluation/onnx.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#109 Mv cache to manager to solve conflict
  README.md
  docs/quick-start.md
  examples/benchmark/benchmark_sqlite_faiss_onnx.py
  examples/data_manager/map_manager.py
  examples/data_manager/scalar_store.py
  examples/data_manager/vector_store.py
  examples/embedding/onnx.py
  examples/embedding/random.py
  examples/langchain_examples/langchain_similaritycache_openai.py
  examples/openai_examples/basic_usage.py
  examples/openai_examples/readme.py
  examples/similarity_evaluation/onnx.py
  examples/similarity_evaluation/search_distance.py
  gptcache/__init__.py
  gptcache/manager/__init__.py
  gptcache/manager/data_manager.py
  gptcache/manager/eviction.py
  gptcache/manager/factory.py
  gptcache/manager/scalar_data/__init__.py
  gptcache/manager/scalar_data/base.py
  gptcache/manager/scalar_data/sqlalchemy.py
  gptcache/manager/vector_data/__init__.py
  gptcache/manager/vector_data/base.py
  gptcache/manager/vector_data/chroma.py
  gptcache/manager/vector_data/faiss.py
  gptcache/manager/vector_data/milvus.py
  tests/integration_tests/examples/map/map.py
  tests/integration_tests/examples/sqlite_faiss_mock/sqlite_faiss_mock.py
  tests/integration_tests/examples/sqlite_faiss_onnx/sqlite_faiss_onnx.py
  tests/integration_tests/test_sqlite_faiss_onnx.py
  tests/unit_tests/cache/test_chromadb.py
  tests/unit_tests/cache/test_eviction.py
  tests/unit_tests/cache/test_map.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#110 Add workflow for pylint
  .github/workflows/pylint.yaml
Labels: dco-passed, ci-passed, approved, lgtm, size/S

#111 Improve chart
  docs/GPTCacheStructure.png
Labels: dco-passed, size/XS, kind/improvement

#113 Modify the What is GPTCache part
  README.md
Labels: dco-passed, size/XS

#114 Fix API reference due to module change
  docs/references/cache.rst
  docs/references/core.rst
  docs/references/gptcache.rst
  docs/references/index.rst
  docs/references/manager.rst
Labels: dco-passed, size/M

#116 Update README.md
  README.md
Labels: dco-passed, approved, size/XS

#118 Improve readme
  README.md
Labels: dco-passed, size/XS, kind/improvement

#117 Update the example doc
  README.md
  docs/system.md
  examples/README.md
  setup.py
Labels: dco-passed, approved, size/L

#120 Change check marks in modules
  docs/modules/cache_manager.md
  docs/modules/cache_storage.md
  docs/modules/embedding_generator.md
  docs/modules/llm_adapter.md
  docs/modules/similarity_evaluator.md
Labels: dco-passed, size/M

#121 Update the readme doc
  README.md
  docs/usage.md
  examples/similarity_evaluation/exact_match.py
  gptcache/__init__.py
  setup.py
Labels: dco-passed, ci-passed, approved, size/L

#124 Update readme
  README.md
Labels: dco-passed, size/XS, kind/improvement

#125 Update the contributing doc
  docs/contributing.md
Labels: dco-passed, approved, size/M

#126 Update docs with change in README
  docs/autodoc_md/gptcache/__init__.md
  docs/autodoc_md/gptcache/cache/__init__.md
  docs/autodoc_md/gptcache/cache/data_manager.md
  docs/autodoc_md/gptcache/cache/factory.md
  docs/autodoc_md/gptcache/core.md
  docs/autodoc_md/index.rst
  docs/autodoc_md/requirements.md
  docs/autodoc_md/setup.md
  docs/conf.py
  docs/index.rst
  docs/modules/cache_manager.md
  docs/modules/cache_storage.md
  docs/modules/embedding_generator.md
  docs/modules/llm_adapter.md
  docs/modules/similarity_evaluator.md
  docs/modules/vector_store.md
  docs/quick-start.md
Labels: dco-passed, size/XL

#127 Update foots
  docs/_templates/author.html
  docs/_templates/copyright.html
  docs/index.rst
Labels: dco-passed, size/S

#128 Add more API references
  docs/references/index.rst
  docs/references/manager.rst
Labels: dco-passed, size/S

#129 Update the benchmark result
  examples/README.md
  examples/benchmark/benchmark_sqlite_faiss_onnx.py
  gptcache/manager/scalar_data/sqlalchemy.py
  tests/integration_tests/common/common_type.py
  tests/integration_tests/examples/sqlite_faiss_mock/sqlite_faiss_mock.py
  tests/integration_tests/examples/sqlite_faiss_onnx/sqlite_faiss_onnx.py
Labels: dco-passed, approved, size/S

#130 Update docs
  docs/index.rst
Labels: dco-passed, kind/improvement, size/S

#131 Update index.rst for changes in README
  docs/index.rst
  docs/references/adapter.rst
  docs/references/gptcache.rst
  docs/references/processor.rst
  docs/references/utils.rst
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#133 Add workflow lint & linckcheck
  .github/workflows/linkcheck.yaml
  .github/workflows/lint.yaml
  .github/workflows/pylint.yaml
  Makefile
  poetry.lock
  poetry.toml
  pylint.conf
  pyproject.toml
Labels: dco-passed, ci-passed, approved, lgtm, size/XXL

#134 Make the cached result more similar to openAI response
  gptcache/adapter/openai.py
Labels: dco-passed, ci-passed, approved, size/S

#135 Update get_data_manager with CacheBase and VectorBase
  README.md
  docs/contributing.md
  docs/usage.md
  examples/README.md
  examples/benchmark/benchmark_sqlite_faiss_onnx.py
  examples/data_manager/map_manager.py
  examples/data_manager/scalar_store.py
  examples/data_manager/vector_store.py
  examples/embedding/onnx.py
  examples/embedding/random.py
  examples/langchain_examples/langchain_similaritycache_openai.py
  examples/openai_examples/basic_usage.py
  examples/openai_examples/readme.py
  examples/similarity_evaluation/onnx.py
  examples/similarity_evaluation/search_distance.py
  gptcache/__init__.py
  gptcache/manager/__init__.py
  gptcache/manager/data_manager.py
  gptcache/manager/eviction.py
  gptcache/manager/factory.py
  gptcache/manager/scalar_data/__init__.py
  gptcache/manager/scalar_data/base.py
  gptcache/manager/scalar_data/manager.py
  gptcache/manager/scalar_data/sqlalchemy.py
  gptcache/manager/vector_data/__init__.py
  gptcache/manager/vector_data/chroma.py
  gptcache/manager/vector_data/faiss.py
  gptcache/manager/vector_data/manager.py
  gptcache/manager/vector_data/milvus.py
  tests/integration_tests/examples/map/map.py
  tests/integration_tests/examples/sqlite_faiss_mock/sqlite_faiss_mock.py
  tests/integration_tests/examples/sqlite_faiss_onnx/sqlite_faiss_onnx.py
  tests/integration_tests/test_sqlite_faiss_onnx.py
  tests/unit_tests/manager/test_chromadb.py
  tests/unit_tests/manager/test_eviction.py
  tests/unit_tests/manager/test_map.py
Labels: dco-passed, ci-passed, approved, lgtm, size/XL

#137 Update the contributing doc
  docs/contributing.md
Labels: dco-passed, approved, size/XS

#136 Improve the adapter test case
  tests/unit_tests/adapter/test_adapter.py
Labels: approved, size/S

#138 Add CI for dev branch
  .github/mergify.yml
  .github/workflows/CI_integration_test_main.yaml
  .github/workflows/CI_main.yaml
  .github/workflows/Nightly_CI_main.yaml
  .github/workflows/build_dev_python_package.yaml
  .github/workflows/linkcheck.yaml
  .github/workflows/lint.yaml
  .github/workflows/pylint.yaml
  .github/workflows/unit_test_main.yaml
  Makefile
Labels: size/M

#143 Prompt before install
  gptcache/utils/dependency_control.py
Labels: approved, size/XS, lgtm

#142 Refactor lazy import
  gptcache/utils/__init__.py
Labels: size/L

#144 Normalize by default
  gptcache/similarity_evaluation/np.py
Labels: size/S

#146 Update the test workflow
  .github/mergify.yml
  .github/workflows/CI_integration_test_main.yaml
  .github/workflows/CI_main.yaml
  .github/workflows/Nightly_CI_main.yaml
  .github/workflows/build_dev_python_package.yaml
  .github/workflows/linkcheck.yaml
  .github/workflows/lint.yaml
  .github/workflows/publish_dev_package.yaml
  .github/workflows/publish_release_package.yaml
  .github/workflows/pylint.yaml
  .github/workflows/unit_test_main.yaml
Labels: dco-passed, approved, size/L

#147 Update the test workflow
  .github/mergify.yml
  .github/workflows/build_dev_python_package.yaml
  .github/workflows/publish_dev_package.yaml
  .github/workflows/publish_release_package.yaml
  .github/workflows/pylint.yaml
Labels: dco-passed, ci-passed, approved, size/S

#145 Update types for ONNX similarity
  gptcache/similarity_evaluation/onnx.py
Labels: dco-passed, size/S

#148 Update usage
  docs/usage.md
Labels: dco-passed, size/M

#149 Update contributing.md emoji
  docs/contributing.md
Labels: dco-passed, approved, size/XS, lgtm

#151 Add the cache factor to make the output more random
  gptcache/adapter/adapter.py
  tests/integration_tests/examples/sqlite_faiss_onnx/sqlite_faiss_onnx.py
  tests/unit_tests/adapter/test_adapter.py
Labels: dco-passed, approved, size/M

#152 Update the pylint and build workflow
  .github/workflows/build_dev_python_package.yaml
  .github/workflows/pylint.yaml
Labels: dco-passed, ci-passed, approved, size/S

#155 Add the function type to the similarity evaluation method
  gptcache/similarity_evaluation/distance.py
  gptcache/similarity_evaluation/exact_match.py
  gptcache/similarity_evaluation/np.py
  gptcache/similarity_evaluation/onnx.py
  gptcache/similarity_evaluation/similarity_evaluation.py
Labels: dco-passed, ci-passed, approved, size/M

#159 Unified the badge style of all icons
  README.md
Labels: dco-passed, approved, size/XS

#161 Improve the test script and workflow
  .github/mergify.yml
  .github/workflows/CI_integration_test_main.yaml
  .github/workflows/CI_main.yaml
  .github/workflows/unit_test_main.yaml
  README.md
  tests/integration_tests/examples/map/test_example_map.py
  tests/integration_tests/examples/sqlite_faiss_mock/test_example_sqlite_faiss.py
  tests/integration_tests/examples/sqlite_faiss_onnx/test_example_sqlite_faiss_onnx.py
Labels: dco-passed, approved, size/L

#160 Update storage with int ids
  gptcache/manager/data_manager.py
  gptcache/manager/eviction.py
  gptcache/manager/scalar_data/base.py
  gptcache/manager/scalar_data/sqlalchemy.py
  gptcache/manager/vector_data/chroma.py
  gptcache/manager/vector_data/faiss.py
  gptcache/manager/vector_data/milvus.py
Labels: dco-passed, size/L

#163 Rebase main to dev branch
  .github/mergify.yml
  setup.py
Labels: dco-passed, approved, size/S

#168 Fix the `cache_skip` param don't take effect
  gptcache/adapter/adapter.py
  setup.py
  tests/unit_tests/adapter/test_adapter.py
Labels: dco-passed, ci-passed, approved, size/S

#167 Add hnswlib
  gptcache/manager/vector_data/__init__.py
  gptcache/manager/vector_data/hnswlib_store.py
  gptcache/manager/vector_data/manager.py
  gptcache/utils/__init__.py
  tests/unit_tests/manager/test_hnswlib_store.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#169 Add codecoverage workflow
  .github/workflows/codecov.yaml
Labels: dco-passed, ci-passed, size/M

#170 Update LangChainLLMs with LLM
  examples/adapter/langchain_llms.py
  examples/langchain_examples/langchain_llms_mock.py
  examples/langchain_examples/langchain_prompt_openai.py
  examples/langchain_examples/langchain_similaritycache_openai.py
  gptcache/adapter/langchain_llms.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#173 Import package with utils
  gptcache/adapter/langchain_llms.py
  gptcache/utils/__init__.py
Labels: dco-passed, ci-passed, approved, lgtm, size/S

#174 Remove `faiss-cpu` version to fix the python 3.10 download error
  gptcache/utils/__init__.py
  gptcache/utils/dependency_control.py
  gptcache/utils/error.py
Labels: dco-passed, ci-passed, approved, size/S

#176 Update the version to `0.1.8`
  setup.py
Labels: dco-passed, approved, size/XS

#181 Add missing file under references
  docs/references/index.rst
Labels: dco-passed, size/XS

#182 Support to import data set
  Makefile
  examples/benchmark/benchmark_sqlite_faiss_onnx.py
  gptcache/__init__.py
  gptcache/manager/data_manager.py
  gptcache/manager/scalar_data/base.py
  gptcache/manager/scalar_data/sqlalchemy.py
  gptcache/manager/vector_data/base.py
  gptcache/manager/vector_data/chroma.py
  gptcache/manager/vector_data/faiss.py
  gptcache/manager/vector_data/hnswlib_store.py
  gptcache/manager/vector_data/milvus.py
  gptcache/utils/error.py
  tests/integration_tests/examples/map/test_example_map.py
  tests/integration_tests/examples/sqlite_faiss_mock/test_example_sqlite_faiss.py
  tests/integration_tests/examples/sqlite_faiss_onnx/test_example_sqlite_faiss_onnx.py
  tests/unit_tests/manager/test_chromadb.py
  tests/unit_tests/manager/test_hnswlib_store.py
Labels: dco-passed, approved, size/L

#183 Update code coverage for dev branch
  .github/mergify.yml
  .github/workflows/unit_test_main.yaml
  tests/integration_tests/test_sqlite_faiss_onnx.py
Labels: dco-passed, ci-passed, approved, lgtm, size/S

#187 Refine vector interface
  gptcache/manager/data_manager.py
  gptcache/manager/vector_data/__init__.py
  gptcache/manager/vector_data/base.py
  gptcache/manager/vector_data/chroma.py
  gptcache/manager/vector_data/faiss.py
  gptcache/manager/vector_data/hnswlib_store.py
  gptcache/manager/vector_data/manager.py
  gptcache/manager/vector_data/milvus.py
  gptcache/utils/__init__.py
  tests/unit_tests/manager/test_hnswlib_store.py
  tests/unit_tests/manager/test_local_index.py
  tests/unit_tests/manager/test_milvusdb.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#186 Add a pre-process function for removing the prompt info
  gptcache/__init__.py
  gptcache/adapter/adapter.py
  gptcache/adapter/openai.py
  gptcache/manager/data_manager.py
  gptcache/processor/pre.py
  gptcache/utils/response.py
  tests/integration_tests/processor/pre/test_pre_without_prompt.py
  tests/unit_tests/processor/test_pre.py
  tests/unit_tests/utils/test_response.py
Labels: dco-passed, ci-passed, approved, size/L

#189 Update the version to `0.1.9`
  setup.py
Labels: dco-passed, approved, size/XS

#190 Update CI timeout
  .github/workflows/unit_test_main.yaml
  setup.py
  tests/requirements.txt
Labels: dco-passed, ci-passed, approved, size/XS, lgtm

#191 Add kreciprocal evaluation.
  gptcache/manager/vector_data/base.py
  gptcache/manager/vector_data/chroma.py
  gptcache/manager/vector_data/faiss.py
  gptcache/manager/vector_data/hnswlib_store.py
  gptcache/manager/vector_data/milvus.py
  gptcache/similarity_evaluation/__init__.py
  gptcache/similarity_evaluation/kreciprocal.py
  tests/unit_tests/similarity_evaluation/test_evaluation_kreciprocal.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#194 Improve coverage testing
  README.md
  codecov.yml
  examples/langchain_examples/langchain_llms_mock.py
  gptcache/embedding/__init__.py
  gptcache/embedding/huggingface.py
  gptcache/embedding/sbert.py
  gptcache/manager/vector_data/chroma.py
  gptcache/similarity_evaluation/__init__.py
  gptcache/utils/__init__.py
  gptcache/utils/error.py
  tests/requirements.txt
  tests/unit_tests/adapter/test_adapter.py
  tests/unit_tests/adapter/test_langchain_llms.py
  tests/unit_tests/adapter/test_openai.py
  tests/unit_tests/embedding/test_cohere.py
  tests/unit_tests/embedding/test_embedding_openai.py
  tests/unit_tests/embedding/test_fasttext.py
  tests/unit_tests/embedding/test_sbert.py
  tests/unit_tests/manager/test_base.py
  tests/unit_tests/manager/test_chromadb.py
  tests/unit_tests/manager/test_milvusdb.py
  tests/unit_tests/similarity_evaluation/test_evaluation_string.py
  tests/unit_tests/similarity_evaluation/test_np.py
  tests/unit_tests/similarity_evaluation/test_simple.py
Labels: dco-passed, ci-passed, approved, size/L

#195 Get_scalar_data return emb
  gptcache/adapter/adapter.py
  gptcache/manager/data_manager.py
  gptcache/manager/scalar_data/sqlalchemy.py
  tests/unit_tests/manager/test_map.py
Labels: dco-passed, ci-passed, approved, lgtm, size/S

#193 Add chatmodels for langchain
  examples/adapter/langchain_llms.py
  examples/langchain_examples/langchain_llms_mock.py
  examples/langchain_examples/langchain_prompt_openai.py
  examples/langchain_examples/langchain_similaritycache_openai.py
  gptcache/adapter/adapter.py
  gptcache/adapter/langchain_llms.py
  gptcache/adapter/langchain_models.py
  gptcache/manager/data_manager.py
  tests/unit_tests/adapter/test_langchain_llms.py
  tests/unit_tests/adapter/test_langchain_models.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#196 Add langchain examples
  docs/examples/langchain/qa_generation.ipynb
  docs/examples/langchain/question_answering.ipynb
  docs/examples/langchain/sqlite.ipynb
Labels: dco-passed, approved, lgtm, size/XXL

#199 Enable Python syntax highlighting
  docs/usage.md
Labels: dco-passed, ci-passed, approved, lgtm, size/S

#203 Update docstring for manager
  gptcache/manager/data_manager.py
  gptcache/manager/eviction.py
  gptcache/manager/factory.py
  gptcache/manager/scalar_data/__init__.py
  gptcache/manager/scalar_data/sqlalchemy.py
  gptcache/manager/vector_data/__init__.py
  gptcache/manager/vector_data/chroma.py
  gptcache/manager/vector_data/faiss.py
  gptcache/manager/vector_data/hnswlib_store.py
  gptcache/manager/vector_data/milvus.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#204 Use inheritance to adapt openai
  gptcache/adapter/openai.py
Labels: dco-passed, ci-passed, approved, size/M

#207 Add openai bootcamp
  docs/bootcamp/langchain/qa_generation.ipynb
  docs/bootcamp/langchain/question_answering.ipynb
  docs/bootcamp/langchain/sqlite.ipynb
  docs/bootcamp/openai/chat.ipynb
  docs/bootcamp/openai/language_translate.ipynb
  docs/bootcamp/openai/sql_translate.ipynb
  docs/toc.bak
Labels: dco-passed, ci-passed, approved, lgtm, size/XL

#206 Update kreciprocal evaluation.
  gptcache/similarity_evaluation/kreciprocal.py
  tests/unit_tests/similarity_evaluation/test_evaluation_kreciprocal.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#210 Update the docstring
  gptcache/manager/factory.py
  gptcache/manager/scalar_data/__init__.py
  gptcache/manager/vector_data/__init__.py
Labels: dco-passed, ci-passed, approved, lgtm, size/S

#208 Add openai.Image.create in adapter
  examples/openai_examples/create_image.py
  gptcache/adapter/openai.py
  gptcache/utils/__init__.py
  gptcache/utils/response.py
  tests/unit_tests/adapter/test_openai.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#205 Refine scalar storage
  gptcache/manager/data_manager.py
  gptcache/manager/eviction.py
  gptcache/manager/scalar_data/base.py
  gptcache/manager/scalar_data/manager.py
  gptcache/manager/scalar_data/sql_storage.py
  gptcache/manager/scalar_data/sqlalchemy.py
  tests/unit_tests/manager/test_eviction.py
  tests/unit_tests/manager/test_sql_scalar.py
Labels: dco-passed, ci-passed, approved, lgtm, size/XL

#211 Improve the langchain example
  docs/release_note.md
  examples/adapter/langchain_llms.py
  examples/langchain_examples/langchain_prompt_openai.py
  examples/langchain_examples/langchain_similaritycache_openai.py
Labels: dco-passed, ci-passed, approved, size/L

#212 Update the version to `0.1.11`
  docs/release_note.md
  setup.py
Labels: dco-passed, approved, size/M

#213 Add object storage
  gptcache/adapter/adapter.py
  gptcache/adapter/langchain_models.py
  gptcache/adapter/openai.py
  gptcache/manager/__init__.py
  gptcache/manager/data_manager.py
  gptcache/manager/factory.py
  gptcache/manager/object_data/__init__.py
  gptcache/manager/object_data/base.py
  gptcache/manager/object_data/local_storage.py
  gptcache/manager/object_data/manager.py
  gptcache/manager/object_data/s3_storage.py
  gptcache/manager/scalar_data/base.py
  gptcache/manager/scalar_data/sql_storage.py
  gptcache/utils/__init__.py
  tests/integration_tests/examples/map/test_example_map.py
  tests/requirements.txt
  tests/unit_tests/manager/test_factory.py
  tests/unit_tests/manager/test_object_storage.py
  tests/unit_tests/manager/test_sql_scalar.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#214 Only when the eviction policy is LRU, the data access_time is updated
  gptcache/adapter/adapter.py
  gptcache/manager/data_manager.py
  gptcache/manager/eviction.py
Labels: dco-passed, ci-passed, approved, lgtm, size/S

#216 Add logger for gptcache
  gptcache/__init__.py
  gptcache/manager/data_manager.py
  gptcache/manager/object_data/local_storage.py
  gptcache/manager/object_data/s3_storage.py
  gptcache/manager/vector_data/milvus.py
  gptcache/utils/dependency_control.py
  gptcache/utils/log.py
  tests/unit_tests/utils/test_log.py
Labels: dco-passed, size/M

#217 The llm request can customize topk search parameters
  gptcache/adapter/adapter.py
  gptcache/manager/data_manager.py
  gptcache/manager/vector_data/faiss.py
  setup.py
Labels: dco-passed, ci-passed, approved, size/S

#218 Scalar return emb in ndarray
  gptcache/manager/scalar_data/sql_storage.py
Labels: dco-passed, ci-passed, approved, size/XS, lgtm

#220 Add openai audio adapter
  gptcache/adapter/openai.py
  gptcache/processor/pre.py
  gptcache/utils/response.py
  tests/unit_tests/adapter/test_openai.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#221 Improve data eviction implementation
  gptcache/manager/data_manager.py
  gptcache/manager/eviction/__init__.py
  gptcache/manager/eviction/base.py
  gptcache/manager/eviction/manager.py
  gptcache/manager/eviction/memory_cache.py
  gptcache/manager/eviction_manager.py
  gptcache/manager/object_data/manager.py
  gptcache/manager/scalar_data/base.py
  gptcache/manager/scalar_data/manager.py
  gptcache/manager/scalar_data/sql_storage.py
  gptcache/manager/vector_data/manager.py
  gptcache/utils/error.py
  tests/unit_tests/eviction/test_memory_cache.py
  tests/unit_tests/manager/test_base.py
  tests/unit_tests/manager/test_eviction.py
  tests/unit_tests/manager/test_sql_scalar.py
  tests/unit_tests/utils/test_error.py
Labels: dco-passed, ci-passed, approved, size/L

#222 Update the version to `0.1.13`
  README.md
  docs/release_note.md
  setup.py
Labels: dco-passed, approved, size/M

#224 Fix to fail to save the data to cache
  gptcache/adapter/openai.py
  gptcache/utils/response.py
  setup.py
  tests/unit_tests/adapter/test_openai.py
Labels: dco-passed, approved, size/L

#225 Update kreciprocal docstring for updated data store interface.
  gptcache/similarity_evaluation/kreciprocal.py
Labels: dco-passed, ci-passed, approved, size/XS, lgtm

#229 Add docstring for openai
  gptcache/adapter/openai.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#227 Add `GPTCache api`, makes it easier to access other different llm mod…
  examples/adapter/api.py
  gptcache/adapter/api.py
  gptcache/processor/post.py
  tests/unit_tests/adapter/test_api.py
  tests/unit_tests/adapter/test_langchain_models.py
  tests/unit_tests/processor/test_post.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#230 Avoid Pillow installation for openai chat
  gptcache/adapter/openai.py
Labels: dco-passed, ci-passed, approved, lgtm, size/S

#231 Add image generation bootcamp
  docs/bootcamp/assets/image_generation_gradio.png
  docs/bootcamp/openai/image_generation.ipynb
  gptcache/adapter/openai.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#232 Update docstring for similarity evaluation.
  gptcache/similarity_evaluation/distance.py
  gptcache/similarity_evaluation/exact_match.py
  gptcache/similarity_evaluation/kreciprocal.py
  gptcache/similarity_evaluation/np.py
  gptcache/similarity_evaluation/onnx.py
  tests/unit_tests/similarity_evaluation/test_np.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#233 Reorganized the `__init__` file in the gptcache dir
  examples/adapter/api.py
  gptcache/__init__.py
  gptcache/adapter/adapter.py
  gptcache/adapter/openai.py
  gptcache/config.py
  gptcache/core.py
  gptcache/report.py
  gptcache/similarity_evaluation/__init__.py
  gptcache/utils/cache_func.py
  gptcache/utils/time.py
  tests/integration_tests/processor/pre/test_pre_without_prompt.py
  tests/unit_tests/adapter/test_adapter.py
  tests/unit_tests/adapter/test_api.py
  tests/unit_tests/test_core.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#236 Update the version to `0.1.15`
  docs/release_note.md
  setup.py
Labels: dco-passed, approved, size/S

#234 Adapt StableDiffusion
  examples/diffusers_examples/stable_diffusion.py
  gptcache/adapter/diffusers.py
  gptcache/utils/__init__.py
  tests/unit_tests/adapter/test_diffusers.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#238 Add audio embedding with data2vec
  gptcache/embedding/__init__.py
  gptcache/embedding/data2vec.py
  gptcache/utils/__init__.py
  tests/unit_tests/embedding/test_data2vec.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#235 Support multi-model question
  gptcache/adapter/adapter.py
  gptcache/adapter/api.py
  gptcache/adapter/langchain_models.py
  gptcache/adapter/openai.py
  gptcache/manager/data_manager.py
  gptcache/manager/scalar_data/base.py
  gptcache/manager/scalar_data/sql_storage.py
  tests/unit_tests/adapter/test_adapter.py
  tests/unit_tests/manager/test_factory.py
  tests/unit_tests/manager/test_sql_scalar.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#239 Add speech to text bootcamp
  docs/bootcamp/assets/speech_to_text_gradio.png
  docs/bootcamp/openai/speech_to_text.ipynb
  docs/toc.bak
  gptcache/embedding/data2vec.py
  gptcache/processor/pre.py
  tests/unit_tests/adapter/test_openai.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm
