Repository zilliztech/GPTCache, pull requests merged in 2023-06, with the labels that each got.

#401 Add the saved token report, auto flush data
  gptcache/__init__.py
  gptcache/adapter/adapter.py
  gptcache/adapter/api.py
  gptcache/adapter/openai.py
  gptcache/config.py
  gptcache/report.py
  gptcache/utils/__init__.py
  gptcache/utils/token.py
  gptcache_server/server.py
  tests/unit_tests/embedding/test_uform.py
  tests/unit_tests/test_client.py
  tests/unit_tests/test_core.py
Labels: dco-passed, ci-passed, approved, size/L

#405 Use the fastapi to improve the GPTCache server
  docs/usage.md
  examples/README.md
  gptcache/client.py
  gptcache/utils/__init__.py
  gptcache_server/__init__.py
  gptcache_server/server.py
  tests/unit_tests/test_client.py
Labels: dco-passed, ci-passed, approved, size/L

#406 Update the version to `0.1.29`
  docs/release_note.md
  gptcache/__init__.py
  gptcache/manager/vector_data/manager.py
  gptcache/manager/vector_data/usearch.py
  tests/unit_tests/manager/test_usearch.py
Labels: dco-passed, ci-passed, approved, size/M

#404 Add input summarization.
  gptcache/adapter/adapter.py
  gptcache/config.py
  gptcache/processor/context/__init__.py
  gptcache/processor/context/summarization_context.py
  tests/unit_tests/adapter/test_adapter.py
  tests/unit_tests/processor/test_summarize_context.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#409 Langchain track token usage
  gptcache/adapter/langchain_models.py
  gptcache/manager/vector_data/usearch.py
  tests/requirements.txt
Labels: dco-passed, approved, size/L

#410 Support to download the cache files
  gptcache/adapter/adapter.py
  gptcache/adapter/api.py
  gptcache_server/server.py
  tests/unit_tests/adapter/test_adapter.py
  tests/unit_tests/adapter/test_langchain_models.py
Labels: dco-passed, ci-passed, approved, size/L

#421 Raise the same type's error for the openai
  gptcache/adapter/openai.py
  gptcache/utils/error.py
  tests/unit_tests/adapter/test_openai.py
  tests/unit_tests/utils/test_error.py
Labels: dco-passed, approved, size/L

#420 Add sequence match evaluation.
  examples/similarity_evaluation/sequence_match.py
  gptcache/adapter/api.py
  gptcache/config.py
  gptcache/processor/pre.py
  gptcache/similarity_evaluation/__init__.py
  gptcache/similarity_evaluation/sequence_match.py
  tests/unit_tests/processor/test_pre.py
  tests/unit_tests/similarity_evaluation/test_evaluation_sequence.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#424 Improve SequenceMatchEvaluation for several cases.
  gptcache/processor/pre.py
  gptcache/similarity_evaluation/sequence_match.py
  tests/unit_tests/processor/test_pre.py
  tests/unit_tests/similarity_evaluation/test_evaluation_sequence.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#425 Change the evaluation score of sequence evaluation to be larger as th…
  examples/similarity_evaluation/sequence_match.py
  gptcache/similarity_evaluation/sequence_match.py
Labels: dco-passed, ci-passed, approved, size/XS, lgtm

#428 Add SBERT CrossEncoder evaluation.
  gptcache/adapter/api.py
  gptcache/similarity_evaluation/__init__.py
  gptcache/similarity_evaluation/sbert_crossencoder.py
  tests/unit_tests/similarity_evaluation/test_evaluation_sbert.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#429 Update the version to `0.1.31`
  docs/release_note.md
  gptcache/__init__.py
  gptcache/similarity_evaluation/cohere_rerank.py
  gptcache/similarity_evaluation/time.py
Labels: dco-passed, approved, size/L

#430 Fix context_len in config
  gptcache/config.py
Labels: dco-passed, size/XS

#431 Fix sequence match example
  examples/similarity_evaluation/sequence_match.py
Labels: dco-passed, ci-passed, approved, size/XS, lgtm

#432 Add the Redis vector store
  .github/workflows/unit_test_main.yaml
  examples/data_manager/vector_store.py
  gptcache/manager/data_manager.py
  gptcache/manager/vector_data/manager.py
  gptcache/manager/vector_data/redis_vectorstore.py
  gptcache/utils/__init__.py
  tests/unit_tests/adapter/test_diffusers.py
  tests/unit_tests/adapter/test_stability.py
  tests/unit_tests/embedding/test_timm.py
  tests/unit_tests/embedding/test_vit.py
  tests/unit_tests/manager/test_chromadb.py
  tests/unit_tests/manager/test_local_index.py
  tests/unit_tests/manager/test_pgvector.py
  tests/unit_tests/manager/test_redis.py
  tests/unit_tests/processor/test_selective_context.py
  tests/unit_tests/processor/test_summarize_context.py
Labels: ci-passed, needs-dco, approved, size/L

#434 Updated link to langchain instructions
  README.md
Labels: needs-dco, size/XS

#440 Fix the eviction error
  gptcache/manager/eviction/manager.py
  gptcache/manager/eviction/memory_cache.py
  tests/unit_tests/eviction/test_memory_cache.py
Labels: dco-passed, approved, size/M

#445 [Feature] search only operation support
  gptcache/adapter/adapter.py
Labels: needs-dco, size/XS

#449 T10H-85 - VectorBase change for namespace allocation
  gptcache/manager/vector_data/manager.py
  gptcache/manager/vector_data/redis_vectorstore.py
Labels: dco-passed, ci-passed, size/XS

#452 Correct the wrong search return value in the Redis vector store.
  gptcache/manager/vector_data/redis_vectorstore.py
  gptcache/utils/dependency_control.py
  tests/unit_tests/manager/test_redis.py
Labels: dco-passed, ci-passed, approved, size/M

#448 [Feature] Cache consistency check for Chroma & Milvus
  gptcache/adapter/adapter.py
  gptcache/manager/vector_data/base.py
  gptcache/manager/vector_data/chroma.py
  gptcache/manager/vector_data/milvus.py
  gptcache/similarity_evaluation/distance.py
  tests/integration_tests/test_sqlite_milvus_sbert.py
Labels: needs-dco, size/L

#453 Add support for Qdrant Vector Store
  gptcache/manager/vector_data/manager.py
  gptcache/manager/vector_data/qdrant.py
  gptcache/utils/__init__.py
  tests/unit_tests/manager/test_qdrant.py
Labels: needs-dco, size/L

#457 Fix the pylint error and add the chromadb test
  gptcache/adapter/adapter.py
  gptcache/config.py
  gptcache/manager/vector_data/chroma.py
  gptcache/manager/vector_data/qdrant.py
  tests/integration_tests/test_sqlite_milvus_sbert.py
  tests/unit_tests/embedding/test_sbert.py
  tests/unit_tests/manager/test_chromadb.py
Labels: dco-passed, approved, size/L

#454 [add] support for mongodb storage
  .github/workflows/unit_test_main.yaml
  gptcache/manager/scalar_data/manager.py
  gptcache/manager/scalar_data/mongo.py
  gptcache/utils/__init__.py
  tests/unit_tests/manager/test_mongo.py
Labels: needs-dco, size/L

#460 Fix the wrong return value of onnx similarity evaluation
  gptcache/adapter/adapter.py
  gptcache/manager/scalar_data/manager.py
  gptcache/processor/post.py
  gptcache/similarity_evaluation/distance.py
  gptcache/similarity_evaluation/onnx.py
  gptcache/utils/softmax.py
  tests/requirements.txt
  tests/unit_tests/similarity_evaluation/test_evaluation_onnx.py
Labels: dco-passed, approved, size/S
