Repository zilliztech/GPTCache, pull requests merged in 2023-09, with the labels that each got.

#531 feat: Add scalar storage support for DynamoDB
  .github/workflows/unit_test_main.yaml
  README.md
  docs/contributing.md
  examples/README.md
  examples/data_manager/scalar_store.py
  gptcache/manager/scalar_data/dynamo_storage.py
  gptcache/manager/scalar_data/manager.py
  tests/unit_tests/manager/test_dynamo_storage.py
Labels: dco-passed, size/XL

#513 Support caching of async completion and cache completion
  gptcache/adapter/adapter.py
  gptcache/adapter/openai.py
  tests/unit_tests/adapter/test_openai.py
Labels: dco-passed, size/L

#538 Fix the langchain chat pydantic bug
  gptcache/adapter/langchain_models.py
  gptcache/adapter/openai.py
  tests/requirements.txt
  tests/unit_tests/test_client.py
Labels: dco-passed, approved, size/S

#539 [mod] updated docs for scalar/vector storage, distributed caching and…
  README.md
  docs/GPT-Cache-Multinode.png
  docs/GPTCache-Distributed-Search.png
  docs/GPTCache-Local-Search.png
  docs/horizontal-scaling-usage.md
Labels: dco-passed, size/M

#541 bugfix: fix correct dependency name for redis-om
  gptcache/utils/__init__.py
Labels: needs-dco, size/XS

#542 Add the 'hit callback' func
  gptcache/adapter/adapter.py
  gptcache/utils/__init__.py
  tests/unit_tests/adapter/test_api.py
Labels: dco-passed, ci-passed, approved, size/XS

#543 docs: fix LangChainChat example
  gptcache/adapter/langchain_models.py
Labels: needs-dco, size/XS

#546 Update the version to `0.1.42`
  gptcache/__init__.py
Labels: dco-passed, approved, size/XS
