Repository zilliztech/GPTCache, pull requests merged in 2023-07, with the labels that each got.

#465 [add] support for redis cache storage
  gptcache/manager/scalar_data/manager.py
  gptcache/manager/scalar_data/redis_storage.py
  gptcache/utils/__init__.py
  tests/requirements.txt
  tests/unit_tests/manager/test_redis_cache_storage.py
Labels: ci-passed, needs-dco, size/L

#466 Improve the position of lint comment
  gptcache/manager/scalar_data/base.py
  gptcache/manager/scalar_data/mongo.py
  gptcache/manager/scalar_data/redis_storage.py
  gptcache/manager/scalar_data/sql_storage.py
Labels: dco-passed, ci-passed, approved, size/S

#471 Upgrade the actions/setup-python to v4
  .github/workflows/Nightly_CI_main.yaml
  .github/workflows/build_dev_python_package.yaml
  .github/workflows/publish_dev_package.yaml
  .github/workflows/publish_release_package.yaml
  .github/workflows/pylint.yaml
  .github/workflows/unit_test_main.yaml
Labels: dco-passed, ci-passed, approved, size/S

#472 Add the report table
  gptcache/adapter/adapter.py
  gptcache/manager/data_manager.py
  gptcache/manager/scalar_data/base.py
  gptcache/manager/scalar_data/mongo.py
  gptcache/manager/scalar_data/redis_storage.py
  gptcache/manager/scalar_data/sql_storage.py
Labels: dco-passed, approved, size/L

#473 Update the version to `0.1.35`
  docs/release_note.md
  gptcache/__init__.py
  gptcache/utils/log.py
Labels: dco-passed, approved, size/S

#477 Add the get `redis` and `mongo` store examples in the reference doc
  docs/configure_it.md
  gptcache/manager/scalar_data/mongo.py
  gptcache/manager/scalar_data/redis_storage.py
Labels: dco-passed, approved, size/M

#480 Listen as an OpenAI Complete API
  gptcache/utils/__init__.py
  gptcache_server/server.py
  tests/unit_tests/adapter/test_adapter.py
  tests/unit_tests/embedding/test_langchain.py
Labels: dco-passed, approved, size/L

#483 Dev
  docs/bootcamp/vertex/index.rst
  docs/bootcamp/vertex/vertexai_caching.ipynb
  docs/toc.bak
Labels: dco-passed, size/XL

#487 Bugfix/#486: provide redis_connection for creating all Object Models
  gptcache/manager/scalar_data/redis_storage.py
  tests/unit_tests/manager/test_redis_cache_storage.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#492 Use the old version for the chromadb
  gptcache/utils/__init__.py
  tests/requirements.txt
Labels: dco-passed, ci-passed, approved, size/XS

#493 added support for weaviate vector databse
  examples/data_manager/vector_store.py
  gptcache/manager/vector_data/manager.py
  gptcache/manager/vector_data/weaviate.py
  gptcache/utils/__init__.py
  pylint.conf
  tests/unit_tests/manager/test_weaviate.py
Labels: dco-passed, ci-passed, approved, size/L, lgtm

#494 Update the version to `0.1.37`
  docs/release_note.md
  gptcache/__init__.py
Labels: dco-passed, ci-passed, approved, size/XS

#495 Handle openai change of api base for just embeddings
  gptcache/embedding/openai.py
Labels: needs-dco, size/S

#500 added support for custom class schema in weaviate vector store
  gptcache/manager/vector_data/manager.py
  gptcache/manager/vector_data/weaviate.py
  tests/unit_tests/manager/test_weaviate.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#501 Fix the error: 'SSDataManager' object has no attribute
  gptcache/manager/data_manager.py
Labels: dco-passed, approved, size/XS
